// -----------------------------------------------------------------------------
// Project:		EXTENDED LIFE SIMULATION CAPSTONE ASSIGNMENT
// Item:		Simulation Analysis
// Requirement:	Event Log
// Author:		Caden Nieves
// Date:		03/04/2026
// Version:		0.3.0
//
// Description:
//    Handles writing snapshot data to a JSON log file. Creates a
//    new timestamped log file at simulation start and continuously appends
//    population snapshots during runtime.
// -----------------------------------------------------------------------------

using System.IO;
using UnityEngine;

/// <summary>
/// Creates & Maintains simulation log file. Converts PopSnapshot objects to
/// JSON format and appends to disk.
/// </summary>
public class SimulationLogger : MonoBehaviour
{
    public string filepath;

    public LogManager logManager;

    public static SimulationLogger Instance;

    /// <summary>
    /// Allows instances of SimulationLogger to be created and accessed across scripts.
    /// </summary>
    void Awake( ) { Instance = this; }


    void OnEnable()
    {
        MapGenerator2D.OnMapGenerated += BeginLoggingSession;
    }

    void OnDisable()
    {
        MapGenerator2D.OnMapGenerated -= BeginLoggingSession;
    }

    /// <summary> Creates a new log file when the user generates a map (Generate Map), not on scene load / main menu. </summary>
    public void BeginLoggingSession()
    {
        string timestamp = System.DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");

        string exeDir = System.IO.Path.GetDirectoryName(Application.dataPath);
        string logDir = System.IO.Path.Combine(exeDir, "Logs");

        System.IO.Directory.CreateDirectory(logDir);

        filepath = System.IO.Path.Combine(logDir, $"population_log_{timestamp}.json");

        File.WriteAllText(filepath, "");

        Debug.Log("Log file created at: " + filepath);
    }

    /// <summary>
    /// Writes population snapshot to active log file
    /// </summary>
    /// <param name="snapshot">Population total generated by PopTracker Class</param>
    public void SaveToFile(PopSnapshot snapshot)
    {
        if (string.IsNullOrEmpty(filepath))
            return;

        string snapshotJson = JsonUtility.ToJson(snapshot);

        LogEntry entry = new LogEntry("Snapshot", snapshot.tick, snapshotJson);

        string json = JsonUtility.ToJson(entry);

        File.AppendAllText(filepath, json + "\n");
    }

    /// <summary>
    /// Writes triggered event such as Overpopulation to active log file.
    /// </summary>
    /// <param name="eventType">Occured event - i.e. extinction, overpopulation</param>
    /// <param name="message">Event message</param>
    /// <param name="tick">current frame when event triggered</param>
    public void LogEvent(string eventType, string message, int tick)
    {
        if (string.IsNullOrEmpty(filepath))
            return;

        LogEventData eventData = new LogEventData(eventType, tick, message);

        string eventJson = JsonUtility.ToJson(eventData);

        LogEntry entry = new LogEntry("Event", tick, eventJson);

        string json = JsonUtility.ToJson(entry);

        File.AppendAllText(filepath, json + "\n");
    }

    /// <summary>
    /// Writes triggered collisions to active log file.
    /// </summary>
    /// <param name="interactionType">interaction - i.e. fleeing, collision, predation</param>
    /// <param name="source">lifeform that initiated interaction</param>
    /// <param name="target">bystander of interaction</param>
    /// <param name="tick">current tick/frame when interaction triggered</param>
    public void LogInteraction(string interactionType, string source, string target)
    {
        if (string.IsNullOrEmpty(filepath))
            return;

        int tick = logManager.currentTick;

        InteractionData interactionData = new InteractionData(interactionType, source, target);

        string interactionJson = JsonUtility.ToJson(interactionData);

        LogEntry entry = new LogEntry("Interaction", tick, interactionJson);

        string json = JsonUtility.ToJson(entry);

        File.AppendAllText(filepath, json + "\n");
    }
}
