// -----------------------------------------------------------------------------
// Project:		EXTENDED LIFE SIMULATION CAPSTONE ASSIGNMENT
// Item:		Simulation Analysis
// Requirement:	Event Log
// Author:		Caden Nieves
// Date:		03/04/2026
// Version:		0.1.0
//
// Description:
//    Handles writing population snapshot data to a JSON log file. Creates a
//    new timestamped log file at simulation start and continuously appends
//    population snapshots during runtime.
// -----------------------------------------------------------------------------

using System.IO;
using UnityEngine;

/// <summary>
/// Creates & Maintains simulation log file. Converts PopSnapshot objects to
/// JSON format and appends to disk.
/// </summary>
public class SimulationLogger : MonoBehaviour
{
    public string filepath;

    /// <summary>
    /// Generates timestamped file to store the current simulation run.
    /// Initializes logging on simulation start. 
    /// </summary>
    void Start()
    {
        string timestamp = System.DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");

        // Generate File Path
        filepath = Application.persistentDataPath + "/population_log_" + timestamp + ".json";

        // Create file with header
        File.WriteAllText(filepath, "Tick,Plants,Grazers,Predators\n");

        // Print file location to Unity Console
        Debug.Log("Log file created at: " + filepath);
    }

    /// <summary>
    /// Writes population snapshot to active log file
    /// </summary>
    /// <param name="snapshot">Population total generated by PopTracker Class</param>
    public void SaveToFile(PopSnapshot snapshot)
    {
        string json = JsonUtility.ToJson(snapshot);

        File.AppendAllText(filepath, json + "\n");
    }
}
